### ISSUE TITLE
How to turn on FLASHLIGHT when calling video?

### ISSUE THREAD

**Issue by anhtuan871993** [skyway/skyway-android-sdk#13]
I found out and could not find the way to turn on the flash while calling video.
https://bugs.chromium.org/p/chromium/issues/detail?id=485972

It's a problem in Android because to use flashlight is mandatory to use a camera instance even when you don't want to capture video.
E.g.: Enable flashlight in an Android device and then try to open the camera app to take a photo. The camera app cannot start because the camera instance is being used by the flashlight.

Please help me. Thank you!

**Comment by salmoncode** [comment]
Thank you for the report.
As we verified, the current SDK does not provide a way to turn on the light while calling video.
We're sorry for not helping you.
