### ISSUE TITLE
[ConnectOption] metadata property is null when connect with other peer?

### ISSUE THREAD

**Issue by haunguyen** [skyway/skyway-android-sdk#2]
Today, when I was tried to connect with other peer (I was set value for metadata property on ConnectOption) but on my partner side, metadata's value on incoming DataConnection is always null. value of label property is working normal.

__ConnectOption option = new ConnectOption();
option.metadata = "call video";
_data = peer.connect(peerId, option);

Someone help me, please!

Thanks in advance

**Comment by tsu-takahashi** [comment]
Thank you for the report.
We received similar reports from other developers.
We are confirming the details now. Please wait a little while and we'll get back to you as soon as possible.

**Comment by tsu-takahashi** [comment]
This bug is now fixed. 
Please try updating the SDK to v1.0.1. 
We're sorry for the inconvenience.

**Comment by iwashi** [comment]
@haunguyen Things are already resolved and I close this issue. If you still have the problem, feel free to open this issue.
