### ISSUE TITLE
P2P call android sdk

### ISSUE THREAD

**Issue by puneetkansal04** [skyway/skyway-android-sdk#42]
Hi,

I am using p2p calling module. but there is a problem. 1 user is getting multiple incoming calls. So i want that as a user will be connect to one user. that these 2 users will not be show in the list and not receive a call from another user. So that call will not be connect more than one user.

**Comment by ibuibu** [comment]
Thanks for the great feedback. 

We tried to keep this sample as simple as possible for the sample. If you want to make it that way, I think you could disable the call event during the conversation.
