### ISSUE TITLE
How to select other camera devices?

### ISSUE THREAD

**Issue by Lrony** [skyway/skyway-android-sdk#60]
Hi Developer:

Thank you for the great SDK.
Usually this SDK is used on the phone, so the existing API is sufficient.
But, I need to use this SDK on the development board. There are **multiple camera devices** on my development board. So i want to select camera device.But I checked the public API and not found that can select camera devices API.
Is there a API to select camera  devices?

Thank you!

**Comment by ibuibu** [comment]
Thank you for raising this issue.

Currently, Skyway allows you to select the front or back device in the cameraPosition setting of MediaConstraints.
https://webrtc.ecl.ntt.com/en/android-reference/classio_1_1skyway_1_1_peer_1_1_browser_1_1_media_constraints.html#aa7b3371e9412ee9fe1dc7138b719b25d

You can also use the switchCamera function to switch between front and back.
https://webrtc.ecl.ntt.com/en/android-reference/classio_1_1skyway_1_1_peer_1_1_browser_1_1_media_stream.html#ad87c4e1d48b63106b156d309da8a00e5

It is not possible to select a specific camera on a device with more than three cameras.

**Comment by Lrony** [comment]
@ibuibu 
Thank for you reply.
I have another question. Skyway is just a basic video service, right?
If I want to manage the users in the video (contact list), does Skyway provide a fixed field to identify the users?
(PeerID are random, so they cannot be used as unique identifiers)

Looking forward to your reply.
Thank you~

**Comment by ibuibu** [comment]
PeerID can be any string of characters.

https://webrtc.ecl.ntt.com/android-reference/classio_1_1skyway_1_1_peer_1_1_peer.html#a6462592bee517811f1d39e5da01db5d7

If you have any more technical questions about SkyWay, please post them in the following community.

https://support.skyway.io/hc/ja/community/topics
