### ISSUE TITLE
APP crash during a video call

### ISSUE THREAD

**Issue by Lrony** [skyway/skyway-android-sdk#61]
# Description of the problem

APP crash during a video call

# Environment

- OS (ex. Android 10.0)
- Network (WiFi)

# Steps to reproduce the problem

1. Set room mode to MESH or SFU
2. Create and  enter room
3. Another device enter the room
4. Wait a minute or so (time is random)
5. App crash

# Expected behavior

APP runs normally

# Other information (Log etc)

E ACodec  : [OMX.qcom.video.encoder.vp8] failed to set input port definition parameters.
E ACodec  : [OMX.qcom.video.encoder.vp8] configureCodec returning error -1010
I OMX-VENC: venc_dev: WARN: Unsupported eColorFormat 0x7f000789

#01 pc 00000000002f9630  /system/lib64/libskyway.so (BuildId: d391d047b21846e7ed457a35e72b8509803afd76)

**Comment by ibuibu** [comment]
I'm sorry for the inconvenience.

Could you tell me SDK version?

I'll check it out.

**Comment by Lrony** [comment]
Thank for you comment,

- Device model name 
  I don't development on the phone, I development on the Qualcomm board.
  Some of the information:
`
[ro.odm.product.cpu.abilist]: [arm64-v8a,armeabi-v7a,armeabi]
[ro.odm.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.odm.product.cpu.abilist64]: [arm64-v8a]
[ro.product.cpu.abi]: [arm64-v8a]
[ro.product.cpu.abilist]: [arm64-v8a,armeabi-v7a,armeabi]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: [arm64-v8a]
[ro.product.locale]: [en-US]
[ro.vendor.product.cpu.abilist]: [arm64-v8a,armeabi-v7a,armeabi]
[ro.vendor.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.vendor.product.cpu.abilist64]: [arm64-v8a]
`

- The time the error occurred (latest and oldest)
  **11-27 16:35**

- Whether the error is reproduced by the sample app
  **YES**

- Frequency of occurrence
  **occurrence**

- Whether or not the error also occurs when specifying a codec
  I try use H264 and VP9 and VP8, They all make mistakes.
Code:
`
RoomOption option = new RoomOption();
option.mode = RoomOption.RoomModeEnum.MESH;
option.stream = mLocalStream;
option.videoCodec = "H264"/"VP8"/"VP9"
`
But i check logs, the name is OMX.qcom.video.encoder.**vp8** (current option.videoCodec is H264):
`
11-27 16:35:11.513 11603 11922 E MediaCodec: test --- name: OMX.qcom.video.encoder.vp8
...
11-27 16:35:11.525 11603 11922 I MediaCodec: test1--- format=AMessage(what = 0x00000000) = {
11-27 16:35:11.525 11603 11922 I MediaCodec:   int32_t color-format = 2130708361
11-27 16:35:11.525 11603 11922 I MediaCodec:   int32_t i-frame-interval = 100
11-27 16:35:11.525 11603 11922 I MediaCodec:   string mime = "video/x-vnd.on2.vp8"
11-27 16:35:11.525 11603 11922 I MediaCodec:   int32_t width = 640
11-27 16:35:11.525 11603 11922 I MediaCodec:   int32_t bitrate-mode = 2
11-27 16:35:11.525 11603 11922 I MediaCodec:   int32_t bitrate = 300000
11-27 16:35:11.525 11603 11922 I MediaCodec:   int32_t frame-rate = 60
11-27 16:35:11.525 11603 11922 I MediaCodec:   int32_t height = 480
11-27 16:35:11.525 11603 11922 I MediaCodec: }
`

**I tried it again today, and it still happens.**

**Comment by Lrony** [comment]
[fullll.log](https://github.com/skyway/skyway-android-sdk/files/7647200/fullll.log)

**Comment by Lrony** [comment]
SDK version: 24

**Comment by ibuibu** [comment]
Thanks for the reply.

We have not seen any crashes on our Android phones (Pixel 3, Huawei P30 Lite).

There are many variations of Android devices, so it is difficult to identify the cause of problems that occur on specific devices.

Also, since we do not have an environment to reproduce the Qualcomm board, we cannot investigate the cause of the problem any further.

Also, we thought that the problem was caused by the server release, so we asked for the time when the error occurred. However, the time you gave us was before the server was released, so we think the problem is probably caused by the device.
