### ISSUE TITLE
Error: E/libEGL: call to OpenGL ES API with no current context (logged once per thread) on Android OS

### ISSUE THREAD

**Issue by 000xuandu** [skyway/skyway-android-sdk#62]
# Description of the problem
Hello @yusuke84, 
I wish you a good day!

I develop a React Native app that uses Skyway Android SDK.
Now, I face the error `E/libEGL: call to OpenGL ES API with no current context (logged once per thread)` each time swipe an item in the list.

# Environment

- React Native 0.66.4
- SDK version: 3.0.1
- Device: Pixel 3
- OS:  Android 8.1
- Network: WiFi

# Steps to reproduce the problem

1. Add Skyway Android SDK for React Native: 
https://github.com/micin-jp/react-native-skyway#android

2. In React Native code, I write:

**Init Peer:** 
```
const _connectPeer = () => {
    const peerId = 'PEER_ID_1';
    const targetPeerId = 'rEkbmMvK9vjnBR5D';

    const options = {
      key: Config.SKYWAY_API_KEY,
      domain: 'localhost',
      debug: 3,
    };

    const peer = new SkyWay.Peer(peerId, options);
    peer.connect();
    peer.addEventListener('peer-open', () => {
      console.log('peer-open');
      peer.call(targetPeerId);
    });
    setPeer(peer);
}
```

**List component**
```
<Carousel
        data={stories}
        renderItem={renderItem}
        // others props
/>
```

**RenderItem function:** 
```
const renderItem = ({_, index}: {item: any; index: number}) => {
    return (
      <RenderProductItem
        index={index}
        indexActive={indexActive}
        peer={peer}
        openCartModal={openCartModal}
      />
    );
  };
```

**RenderProductItem like this:**
```
<View style={styles.flex1}>
        {peer ? (
          <SkyWay.RemoteVideo style={styles.remoteVideo} peer={peer} />
        ) : null}
</View>
```

OK, now the UI will be shown a list can swipe (left/right) to see other items.
And when I swipe back and forth the items, the video can not be kept, the video has been disabled.

Video: https://vimeo.com/manage/videos/688005013

# Expected behavior
1. The video can be kept when I swipe items.
2. How to fix `E/libEGL: call to OpenGL ES API with no current context (logged once per thread)` error?

# Other information (Log etc)
Included in the video below.

**Comment by kadoshita** [comment]
@000xuandu Thank you for reporting the issue.
We're sorry, we don't officially support React Native.

Posting on our community forums may provide useful information.
https://support.skyway.io/hc/ja/community/topics/201518848-Android-SDK

If you get the same error in the sample app, please post the issue again.
https://github.com/skyway/skyway-android-sdk/tree/master/examples
