### ISSUE TITLE
Please, fix a bug of `replaceStream` with the audio OR video only stream for sdk android/ios

### ISSUE THREAD

**Issue by trung0123** [skyway/skyway-android-sdk#68]
# Description of the problem

# Environment

- SDK version (ex. SDK v1.0.1,etc)
- Device (ex. Nexus6, etc)
- OS (ex. Android 7.0 etc)
- Network (Cable/DSL/Fiber + WiFi, MiFi, LTE, etc)

# Steps to reproduce the problem

I cannot replace stream audio or video only stream for sdk android/ios, I saw this bug fixed for sdk javascript https://github.com/skyway/skyway-js-sdk/commit/636606476e98c43fcf49b4324aad77127fabc04b. I hope skyway team can fix it.

# Expected behavior

# Other information (Log etc)

**Comment by n-hidaka** [comment]
Thank you for your report.  
We have added this issue to our backlog.  
However, it is not likely to be addressed immediately.
