### ISSUE TITLE
Cannot load local video stream by VideoFileSource??

### ISSUE THREAD

**Issue by trung0123** [skyway/skyway-android-sdk#72]
# Description of the problem

I am testing Video File Source (Experimental API) to test whether it is possible to create local video stream from video source file or not? But the result is not displayed, it shows a black screen. I made sure it created local video stream from code but for some reason it came out black .Please check for me, thank you!

# Environment

- SDK version: New Skyway SDK 1.4.0
- Device: Pixel 5a
- OS Android 13
- Network Wifi

# Steps to reproduce the problem

![image](https://github.com/skyway/skyway-android-sdk/assets/16054629/c4d54df7-cda2-4ce5-87d1-f30ceb2373d8)

![image](https://github.com/skyway/skyway-android-sdk/assets/16054629/072a0bc5-db8f-442a-9a17-8e14857bc638)

![image](https://github.com/skyway/skyway-android-sdk/assets/16054629/a5c3cf19-5dea-4044-889d-0ea71f60f95d)

# Expected behavior

# Other information (Log etc)

**Comment by d-matsui** [comment]
Hi. I'm a developer of the SkyWay.
Thank you for reporting the problem.

This repository is not for the new version of SkyWay.
For technical support related to the new SkyWay, you must subscribe to the Enterprise plan.
For further details, please refer to the [SkyWay Support](https://support.skyway.ntt.com) page.
