### ISSUE TITLE
cannot import "io.skyway.Peer.BaseConnection.SerializationEnum"

### ISSUE THREAD

**Issue by goroya** [skyway/skyway-android-sdk#9]
I cannot import below class  using Java and Kotlin on Android Studio.
 "import io.skyway.Peer.BaseConnection.SerializationEnum"

It is described in the following document
https://webrtc.ecl.ntt.com/android-reference/enumio_1_1skyway_1_1_peer_1_1_base_connection_1_1_serialization_enum.html

Why?

**Comment by perry14** [comment]
'io.skyway.Peer.BaseConnection' is not public in 'io.skyway.Peer'. Cannot be accessed from outside package.
